export class Paciente {
    id!:number;
    terapeuta!:number;
    nombre!:string;
    domicilio!:string;
    fecha_naciemiento!:Date;
    instruccion!:string;
    ocupacion_anterior!:string;
    pasatiempo!:string;
    fecha_ingreso!:Date;
    motivo_ingreso!:string;
    estado_civil!:string;
    nombre_conyuge!:string;
    celular_conyuge!:string;
    nombre_familiar_1!:string;
    parentesco_familiar_1!:string;
    direccion_familiar_1!:string;
    celular_familiar_1!:string;
    nombre_familiar_2!:string;
    parentesco_familiar_2!:string;
    direccion_familiar_2!:string;
    celular_familiar_2!:string;
    diagnostico!:string;
    medicamento!:string;
    doctor!:string;
    movilidad!:string;
    contraindicaciones!:string;
    observacion!:string;
}